// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/module_include_list/module_include_list.go - DO NOT EDIT.

package include

import (
	// Import packages that need to register themselves.
	_ "github.com/elastic/beats/v7/metricbeat/module/ceph"
	_ "github.com/elastic/beats/v7/metricbeat/module/ceph/cluster_disk"
	_ "github.com/elastic/beats/v7/metricbeat/module/ceph/cluster_health"
	_ "github.com/elastic/beats/v7/metricbeat/module/ceph/cluster_status"
	_ "github.com/elastic/beats/v7/metricbeat/module/ceph/mgr_cluster_disk"
	_ "github.com/elastic/beats/v7/metricbeat/module/ceph/mgr_cluster_health"
	_ "github.com/elastic/beats/v7/metricbeat/module/ceph/mgr_osd_perf"
	_ "github.com/elastic/beats/v7/metricbeat/module/ceph/mgr_osd_pool_stats"
	_ "github.com/elastic/beats/v7/metricbeat/module/ceph/mgr_osd_tree"
	_ "github.com/elastic/beats/v7/metricbeat/module/ceph/mgr_pool_disk"
	_ "github.com/elastic/beats/v7/metricbeat/module/ceph/monitor_health"
	_ "github.com/elastic/beats/v7/metricbeat/module/ceph/osd_df"
	_ "github.com/elastic/beats/v7/metricbeat/module/ceph/osd_tree"
	_ "github.com/elastic/beats/v7/metricbeat/module/ceph/pool_disk"
)
